name: wandxinc_login
description: A Very Good Project created by Very Good CLI.
version: 0.3.0+1
publish_to: none

environment:
  sdk: ^3.4.0
  flutter: ^3.22.0

dependencies:
  bloc: ^8.1.4
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  wandxinc_core:
    git:
      url: https://github.com/wandx/wandxinc_core
      ref: v3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
